import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { HarnessError, LoopRefused, ReplayFailed } from "../harness/errors.js";
import { readLog } from "../harness/read-log.js";
import { fromRepoPath } from "../harness/paths.js";
import { createCraftServer } from "../mcp/server.js";
import { loadWorld } from "../sim/loader.js";

export interface RecordedCall {
  seq: number;
  tool: string;
  args: Record<string, unknown>;
  ok: boolean;
  /** The text the agent saw, regenerated by replaying the log on a fresh game. */
  output: string;
  error?: string | undefined;
  crafted?: { item: string; qty: number } | undefined;
  /** From the run's trace. */
  durationMs: number;
}

/** One finished run as the agent saw it. */
export interface Recording {
  /** The run's label inside a loop: `001`, `002`, ... in the order the runs were given. Citations use it. */
  label: string;
  runDir: string;
  goal: { item: string; qty: number };
  /** The world path as the run recorded it. */
  world: string;
  /** The models that ran, from the run's score. */
  models: string[];
  prompt: string;
  calls: RecordedCall[];
  callCount: number;
  finalAnswer: string;
}

const readJson = <T>(path: string): T => JSON.parse(readFileSync(path, "utf8")) as T;

/**
 * Replay a finished run on a fresh game through the real craft server, as scoring does, and collect what the agent
 * saw. A run that is unfinished, whose log does not replay, whose logged craft or refusal differs from the replay's,
 * or whose trace does not pair with its log, is refused and nothing else is done.
 */
export async function replayRun(runDir: string, label: string): Promise<Recording> {
  try {
    return await replay(runDir, label);
  } catch (e) {
    if (e instanceof HarnessError) throw e;
    throw new ReplayFailed("the run could not be replayed", e);
  }
}

async function replay(runDir: string, label: string): Promise<Recording> {
  for (const f of ["score.json", "run.jsonl", "trace.jsonl", "mcp.json", "prompt.txt"]) {
    if (!existsSync(join(runDir, f))) throw new ReplayFailed(`the run folder has no ${f}; the run is unfinished`);
  }
  const score = readJson<{
    text?: string;
    measured?: { trace?: string };
    score?: { goal?: { item: string; qty: number } };
    model?: { requested?: string | null; resolved?: string[] };
  }>(join(runDir, "score.json"));
  if (score.measured?.trace !== "matched") throw new ReplayFailed("the run's trace does not match its log");
  const goal = score.score?.goal;
  if (!goal) throw new ReplayFailed("score.json names no goal");

  const entries = readLog(join(runDir, "run.jsonl"));
  const toolLines = readFileSync(join(runDir, "trace.jsonl"), "utf8")
    .split("\n")
    .filter(Boolean)
    .map((l) => JSON.parse(l) as { kind: string; tool: string; startMs: number; endMs: number })
    .filter((l) => l.kind === "tool");
  if (toolLines.length !== entries.length) throw new ReplayFailed("the trace does not pair with the log");

  const world = readJson<{ mcpServers: { craft: { env: { SIM_WORLD: string } } } }>(join(runDir, "mcp.json")).mcpServers.craft.env.SIM_WORLD;
  const { server } = createCraftServer(loadWorld(fromRepoPath(world)));
  const client = new Client({ name: "critic-loop-replay", version: "0" });
  const [a, b] = InMemoryTransport.createLinkedPair();
  await Promise.all([server.connect(a), client.connect(b)]);

  const calls: RecordedCall[] = [];
  try {
    for (const [i, entry] of entries.entries()) {
      const line = toolLines[i]!;
      const duration = line.endMs - line.startMs;
      if (line.tool !== entry.tool || !Number.isFinite(duration) || duration < 0) throw new ReplayFailed(`trace line ${i + 1} does not match the logged call`);
      const r = (await client.callTool({ name: entry.tool, arguments: entry.args })) as { content: { text: string }[]; isError?: boolean };
      const output = r.content[0]?.text ?? "";
      const body = JSON.parse(output) as { crafted?: { item: string; qty: number }; error?: unknown };
      const ok = !r.isError;
      const error = !ok && body.error !== undefined ? String(body.error) : undefined;
      const crafted = ok ? body.crafted : undefined;
      // As src/sim/score.ts does: the same call can succeed and make something else if the world changed.
      if (ok !== entry.ok) throw new ReplayFailed(`entry ${entry.seq} (${entry.tool}): logged ok=${entry.ok}, replay gave ok=${ok}`);
      if (entry.error !== error) throw new ReplayFailed(`entry ${entry.seq} (${entry.tool}): the refusal differs from the log`);
      if (JSON.stringify(entry.crafted) !== JSON.stringify(crafted)) throw new ReplayFailed(`entry ${entry.seq} (${entry.tool}): what was crafted differs from the log`);
      calls.push({ seq: entry.seq, tool: entry.tool, args: entry.args, ok, output, error, crafted, durationMs: duration });
    }
  } finally {
    await client.close().catch(() => {});
  }

  return {
    label,
    runDir,
    goal,
    world,
    models: score.model?.resolved?.length ? score.model.resolved : score.model?.requested ? [score.model.requested] : [],
    prompt: readFileSync(join(runDir, "prompt.txt"), "utf8"),
    calls,
    callCount: calls.length,
    finalAnswer: score.text ?? "",
  };
}

/** The recording as text for a role: the prompt, every call and what came back, and the final answer. */
export function recordingText(rec: Recording): string {
  const lines = [`# Run ${rec.label}`, "", "## Prompt", "", rec.prompt.trim(), "", "## Calls", ""];
  for (const c of rec.calls) {
    lines.push(`### Call ${c.seq}: ${c.tool} ${JSON.stringify(c.args)}`, `Status: ${c.ok ? "ok" : "refused"}`, "```", c.output.trim(), "```", "");
  }
  lines.push("## Final answer", "", rec.finalAnswer.trim(), "");
  return lines.join("\n");
}

/** Runs recorded together must share a goal and a world; anything else cannot be distilled into one skill. */
export function assertSameTask(recs: readonly Recording[]): void {
  const first = recs[0];
  if (!first) throw new LoopRefused("no runs were given");
  for (const r of recs) {
    if (r.goal.item !== first.goal.item || r.goal.qty !== first.goal.qty) throw new LoopRefused("the runs are for different goals");
    if (r.world !== first.world) throw new LoopRefused("the runs are in different worlds");
  }
}

export const recordingsChars = (recs: readonly Recording[]): number => recs.reduce((n, r) => n + recordingText(r).length, 0);
