/**
 * Spike: write a finished run to NAMS through the REST API, so the teacher's session never runs the hooks
 * (and so never recalls). Outputs are regenerated by replaying the run log through the real craft server,
 * which is deterministic. Usage: tsx ingest.ts <run folder> [--dry]
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createCraftServer } from "../../src/mcp/server.js";
import { loadWorld } from "../../src/sim/loader.js";

const [dir, flag] = process.argv.slice(2);
if (!dir) throw new Error("usage: ingest.ts <run folder> [--dry]");
const dry = flag === "--dry";

const jsonl = (f: string) => readFileSync(join(dir, f), "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l));
const mcp = JSON.parse(readFileSync(join(dir, "mcp.json"), "utf8")).mcpServers.craft.env;
const calls: { tool: string; args: Record<string, unknown>; ok: boolean }[] = jsonl("run.jsonl");
const durations: number[] = jsonl("trace.jsonl").filter((l) => l.kind === "tool").map((l) => Math.max(0, l.endMs - l.startMs));
const prompt = readFileSync(join(dir, "prompt.txt"), "utf8");
const final: string = JSON.parse(readFileSync(join(dir, "score.json"), "utf8")).text;

// Replay on a fresh game through the real server; the text is what the agent saw.
const { server } = createCraftServer(loadWorld(mcp.SIM_WORLD));
const client = new Client({ name: "ingest", version: "0" });
const [a, b] = InMemoryTransport.createLinkedPair();
await Promise.all([server.connect(a), client.connect(b)]);
const replayed: { tool: string; input: string; output: string; status: string; durationMs: number }[] = [];
for (const [i, c] of calls.entries()) {
  const r = (await client.callTool({ name: c.tool, arguments: c.args })) as { content: { text: string }[]; isError?: boolean };
  if (Boolean(r.isError) === c.ok) throw new Error(`replay diverged at call ${i + 1}`);
  replayed.push({ tool: `mcp__craft__${c.tool}`, input: JSON.stringify(c.args), output: r.content[0]!.text, status: r.isError ? "failure" : "success", durationMs: durations[i] ?? 0 });
}
console.log(`replayed ${replayed.length} calls; ${replayed.filter((c) => c.status === "failure").length} refusals; ${new Set(replayed.map((c) => c.tool)).size} distinct tools`);
if (dry) process.exit(0);

const base = "https://memory.neo4jlabs.com/v1";
const headers = { Authorization: `Bearer ${process.env.NAMS_API_KEY}`, "X-Workspace-Id": process.env.NAMS_WORKSPACE_ID ?? "", "Content-Type": "application/json" };
if (!process.env.NAMS_API_KEY || !process.env.NAMS_WORKSPACE_ID) throw new Error("NAMS_API_KEY and NAMS_WORKSPACE_ID must be set");
async function post<T>(path: string, body: object): Promise<T> {
  const res = await fetch(base + path, { method: "POST", headers, body: JSON.stringify(body) });
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  return (await res.json()) as T;
}
const conv = await post<{ id: string }>("/conversations", { metadata: { source: "rest-ingest", run: dir } });
await post(`/conversations/${conv.id}/messages`, { role: "user", content: prompt });
// One step per distinct tool, as the hooks make, so the two recordings are comparable.
const steps = new Map<string, string>();
for (const tool of new Set(replayed.map((c) => c.tool))) {
  const s = await post<{ id: string }>("/reasoning/steps", { conversationId: conv.id, actionTaken: tool, reasoning: `Claude Code ran ${tool} with the provided tool input` });
  steps.set(tool, s.id);
}
for (const c of replayed) await post("/reasoning/tool-calls", { toolName: c.tool, input: c.input, output: c.output, status: c.status, durationMs: c.durationMs, stepId: steps.get(c.tool) });
await post(`/conversations/${conv.id}/messages`, { role: "assistant", content: final });
console.log(`conversation ${conv.id}`);
