/**
 * Spike: turn a finished run into a plain-text transcript of what the agent saw (prompt, each call, each
 * output), so a reader can work from the recording alone. Outputs are regenerated by replaying the run log
 * through the real craft server, as the REST-ingest spike does; the world file is never printed.
 * Usage: tsx transcript.ts <run folder> <output file>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createCraftServer } from "../../src/mcp/server.js";
import { loadWorld } from "../../src/sim/loader.js";

const [dir, out, ...extra] = process.argv.slice(2);
if (!dir || !out || extra.length > 0) throw new Error("usage: transcript.ts <run folder> <output file>");

const calls: { tool: string; args: Record<string, unknown>; ok: boolean }[] = readFileSync(join(dir, "run.jsonl"), "utf8")
  .split("\n").filter(Boolean).map((l) => JSON.parse(l));
const mcp = JSON.parse(readFileSync(join(dir, "mcp.json"), "utf8")).mcpServers.craft.env;
const prompt = readFileSync(join(dir, "prompt.txt"), "utf8");

const { server } = createCraftServer(loadWorld(mcp.SIM_WORLD));
const client = new Client({ name: "transcript", version: "0" });
const [a, b] = InMemoryTransport.createLinkedPair();
await Promise.all([server.connect(a), client.connect(b)]);

const lines = ["# Recorded run", "", "## Prompt", "", prompt.trim(), "", "## Calls", ""];
for (const [i, c] of calls.entries()) {
  const r = (await client.callTool({ name: c.tool, arguments: c.args })) as { content: { text: string }[]; isError?: boolean };
  if (Boolean(r.isError) === c.ok) throw new Error(`replay diverged at call ${i + 1}`);
  lines.push(`### Call ${i + 1}: ${c.tool} ${JSON.stringify(c.args)}`, `Status: ${r.isError ? "refused" : "ok"}`, "```", r.content[0]!.text, "```", "");
}
writeFileSync(out, lines.join("\n"));
console.log(`${out}: ${calls.length} calls`);
